// Package gen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package genbw

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FieldType.
const (
	FieldTypeN0 FieldType = "0"
	FieldTypeN1 FieldType = "1"
	FieldTypeN2 FieldType = "2"
	FieldTypeN3 FieldType = "3"
)

// Defines values for ItemCardBrand.
const (
	Visa ItemCardBrand = "visa"
)

// Defines values for ItemSecureNoteType.
const (
	ItemSecureNoteTypeN0 ItemSecureNoteType = 0
)

// Defines values for ItemTemplateReprompt.
const (
	ItemTemplateRepromptN0 ItemTemplateReprompt = 0
	ItemTemplateRepromptN1 ItemTemplateReprompt = 1
)

// Defines values for ItemTemplateType.
const (
	ItemTemplateTypeN1 ItemTemplateType = 1
	ItemTemplateTypeN2 ItemTemplateType = 2
	ItemTemplateTypeN3 ItemTemplateType = 3
	ItemTemplateTypeN4 ItemTemplateType = 4
)

// Defines values for SendTemplateType.
const (
	SendTemplateTypeN0 SendTemplateType = 0
	SendTemplateTypeN1 SendTemplateType = 1
)

// Defines values for StatusDataObject.
const (
	Template StatusDataObject = "template"
)

// Defines values for StatusDataTemplateStatus.
const (
	Locked          StatusDataTemplateStatus = "locked"
	Unauthenticated StatusDataTemplateStatus = "unauthenticated"
	Unlocked        StatusDataTemplateStatus = "unlocked"
)

// Defines values for UrisMatch.
const (
	UrisMatchN0 UrisMatch = 0
	UrisMatchN1 UrisMatch = 1
	UrisMatchN2 UrisMatch = 2
	UrisMatchN3 UrisMatch = 3
	UrisMatchN4 UrisMatch = 4
	UrisMatchN5 UrisMatch = 5
)

// Defines values for GetObjectTemplateTypeParamsType.
const (
	GetObjectTemplateTypeParamsTypeCollection      GetObjectTemplateTypeParamsType = "collection"
	GetObjectTemplateTypeParamsTypeFolder          GetObjectTemplateTypeParamsType = "folder"
	GetObjectTemplateTypeParamsTypeItem            GetObjectTemplateTypeParamsType = "item"
	GetObjectTemplateTypeParamsTypeItemCard        GetObjectTemplateTypeParamsType = "item.card"
	GetObjectTemplateTypeParamsTypeItemCollections GetObjectTemplateTypeParamsType = "item-collections"
	GetObjectTemplateTypeParamsTypeItemField       GetObjectTemplateTypeParamsType = "item.field"
	GetObjectTemplateTypeParamsTypeItemIdentity    GetObjectTemplateTypeParamsType = "item.identity"
	GetObjectTemplateTypeParamsTypeItemLogin       GetObjectTemplateTypeParamsType = "item.login"
	GetObjectTemplateTypeParamsTypeItemLoginUri    GetObjectTemplateTypeParamsType = "item.login.uri"
	GetObjectTemplateTypeParamsTypeItemSecurenote  GetObjectTemplateTypeParamsType = "item.securenote"
	GetObjectTemplateTypeParamsTypeOrgCollection   GetObjectTemplateTypeParamsType = "org-collection"
)

// Collection defines model for collection.
type Collection struct {
	ExternalId     *string             `json:"externalId,omitempty"`
	Groups         *[]Group            `json:"groups,omitempty"`
	Name           *string             `json:"name,omitempty"`
	OrganizationId *openapi_types.UUID `json:"organizationId,omitempty"`
}

// Deviceapprovallist defines model for deviceapprovallist.
type Deviceapprovallist = []Deviceapprovalproperties

// Deviceapprovalproperties defines model for deviceapprovalproperties.
type Deviceapprovalproperties struct {
	CreationDate            *string `json:"creationDate,omitempty"`
	Email                   *string `json:"email,omitempty"`
	Id                      *string `json:"id,omitempty"`
	RequestDeviceIdentifier *string `json:"requestDeviceIdentifier,omitempty"`
	RequestDeviceType       *string `json:"requestDeviceType,omitempty"`
	RequestIpAddress        *string `json:"requestIpAddress,omitempty"`
	UserId                  *string `json:"userId,omitempty"`
}

// Field defines model for field.
type Field struct {
	Name  *string    `json:"name,omitempty"`
	Type  *FieldType `json:"type,omitempty"`
	Value *string    `json:"value,omitempty"`
}

// FieldType defines model for Field.Type.
type FieldType string

// Folder defines model for folder.
type Folder struct {
	Name *string `json:"name,omitempty"`
}

// Group defines model for group.
type Group struct {
	HidePasswords *bool               `json:"hidePasswords,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	ReadOnly      *bool               `json:"readOnly,omitempty"`
}

// ItemCard defines model for item.card.
type ItemCard struct {
	Brand          *ItemCardBrand `json:"brand,omitempty"`
	CardholderName *string        `json:"cardholderName,omitempty"`
	Code           *string        `json:"code,omitempty"`
	ExpMonth       *string        `json:"expMonth,omitempty"`
	ExpYear        *string        `json:"expYear,omitempty"`
	Number         *string        `json:"number,omitempty"`
}

// ItemCardBrand defines model for ItemCard.Brand.
type ItemCardBrand string

// ItemIdentity defines model for item.identity.
type ItemIdentity struct {
	Address1       *string `json:"address1,omitempty"`
	Address2       *string `json:"address2,omitempty"`
	Address3       *string `json:"address3,omitempty"`
	City           *string `json:"city,omitempty"`
	Company        *string `json:"company,omitempty"`
	Country        *string `json:"country,omitempty"`
	Email          *string `json:"email,omitempty"`
	FirstName      *string `json:"firstName,omitempty"`
	LastName       *string `json:"lastName,omitempty"`
	LicenseNumber  *string `json:"licenseNumber,omitempty"`
	MiddleName     *string `json:"middleName,omitempty"`
	PassportNumber *string `json:"passportNumber,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	PostalCode     *string `json:"postalCode,omitempty"`
	Ssn            *string `json:"ssn,omitempty"`
	State          *string `json:"state,omitempty"`
	Title          *string `json:"title,omitempty"`
	Username       *string `json:"username,omitempty"`
}

// ItemLogin defines model for item.login.
type ItemLogin struct {
	Password *string `json:"password,omitempty"`
	Totp     *string `json:"totp,omitempty"`
	Uris     *Uris   `json:"uris,omitempty"`
	Username *string `json:"username,omitempty"`
}

// ItemSecureNote defines model for item.secureNote.
type ItemSecureNote struct {
	Type *ItemSecureNoteType `json:"type,omitempty"`
}

// ItemSecureNoteType defines model for ItemSecureNote.Type.
type ItemSecureNoteType int

// ItemTemplate defines model for item.template.
type ItemTemplate struct {
	Card           *ItemCard             `json:"card,omitempty"`
	CollectionIds  *[]openapi_types.UUID `json:"collectionIds,omitempty"`
	Favorite       *bool                 `json:"favorite,omitempty"`
	Fields         *[]Field              `json:"fields,omitempty"`
	FolderId       *openapi_types.UUID   `json:"folderId,omitempty"`
	Identity       *ItemIdentity         `json:"identity,omitempty"`
	Login          *ItemLogin            `json:"login,omitempty"`
	Name           *string               `json:"name,omitempty"`
	Notes          *string               `json:"notes,omitempty"`
	OrganizationId *openapi_types.UUID   `json:"organizationId,omitempty"`
	Reprompt       *ItemTemplateReprompt `json:"reprompt,omitempty"`
	SecureNote     *ItemSecureNote       `json:"secureNote,omitempty"`
	Type           *ItemTemplateType     `json:"type,omitempty"`
}

// ItemTemplateReprompt defines model for ItemTemplate.Reprompt.
type ItemTemplateReprompt int

// ItemTemplateType defines model for ItemTemplate.Type.
type ItemTemplateType int

// LockunlockSuccess defines model for lockunlock.success.
type LockunlockSuccess struct {
	Data *struct {
		Message *string `json:"message,omitempty"`
		NoColor *bool   `json:"noColor,omitempty"`
		Object  *string `json:"object,omitempty"`
		Title   *string `json:"title,omitempty"`
	} `json:"data,omitempty"`
	Success *bool `json:"success,omitempty"`
}

// SendTemplate defines model for send.template.
type SendTemplate struct {
	DeletionDate   *time.Time        `json:"deletionDate,omitempty"`
	Disabled       *bool             `json:"disabled,omitempty"`
	ExpirationDate *time.Time        `json:"expirationDate,omitempty"`
	File           *string           `json:"file,omitempty"`
	HideEmail      *bool             `json:"hideEmail,omitempty"`
	MaxAccessCount *int              `json:"maxAccessCount,omitempty"`
	Name           *string           `json:"name,omitempty"`
	Notes          *string           `json:"notes,omitempty"`
	Password       *string           `json:"password,omitempty"`
	Text           *SendText         `json:"text,omitempty"`
	Type           *SendTemplateType `json:"type,omitempty"`
}

// SendTemplateType defines model for SendTemplate.Type.
type SendTemplateType int

// SendText defines model for send.text.
type SendText struct {
	Hidden *bool   `json:"hidden,omitempty"`
	Text   *string `json:"text,omitempty"`
}

// Status defines model for status.
type Status struct {
	Data *struct {
		Object   *StatusDataObject `json:"object,omitempty"`
		Template *struct {
			LastSync  *time.Time                `json:"lastSync,omitempty"`
			ServerUrl *string                   `json:"serverUrl,omitempty"`
			Status    *StatusDataTemplateStatus `json:"status,omitempty"`
			UserEmail *openapi_types.Email      `json:"userEmail,omitempty"`
			UserID    *openapi_types.UUID       `json:"userID,omitempty"`
		} `json:"template,omitempty"`
	} `json:"data,omitempty"`
	Success *bool `json:"success,omitempty"`
}

// StatusDataObject defines model for Status.Data.Object.
type StatusDataObject string

// StatusDataTemplateStatus defines model for Status.Data.Template.Status.
type StatusDataTemplateStatus string

// Uris defines model for uris.
type Uris struct {
	Match *UrisMatch `json:"match,omitempty"`
	Uri   *string    `json:"uri,omitempty"`
}

// UrisMatch defines model for Uris.Match.
type UrisMatch int

// PostAttachmentMultipartBody defines parameters for PostAttachment.
type PostAttachmentMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`
}

// PostAttachmentParams defines parameters for PostAttachment.
type PostAttachmentParams struct {
	// Itemid Unique identifier of the item to attach a file to.
	Itemid openapi_types.UUID `form:"itemid" json:"itemid"`
}

// PostConfirmOrgMemberIdParams defines parameters for PostConfirmOrgMemberId.
type PostConfirmOrgMemberIdParams struct {
	// OrganizationId A unique identifier for the Organization.
	OrganizationId openapi_types.UUID `form:"organizationId" json:"organizationId"`
}

// GetGenerateParams defines parameters for GetGenerate.
type GetGenerateParams struct {
	// Length Number of characters in the **password**.
	Length *int `form:"length,omitempty" json:"length,omitempty"`

	// Uppercase Include uppercase characters in the **password**.
	Uppercase *bool `form:"uppercase,omitempty" json:"uppercase,omitempty"`

	// Lowercase Include lowercase characters in the **password**.
	Lowercase *bool `form:"lowercase,omitempty" json:"lowercase,omitempty"`

	// Number Include numbers in the **password**.
	Number *bool `form:"number,omitempty" json:"number,omitempty"`

	// Special Include special characters in the **password**.
	Special *bool `form:"special,omitempty" json:"special,omitempty"`

	// Passphrase Generate passphrase (by default, `/generate` will generate a password).
	Passphrase *bool `form:"passphrase,omitempty" json:"passphrase,omitempty"`

	// Words Number of words in the **passphrase**.
	Words *int `form:"words,omitempty" json:"words,omitempty"`

	// Separator Separator character in the **passphrase**.
	Separator *string `form:"separator,omitempty" json:"separator,omitempty"`

	// Capitalize Title-case the **passphrase**.
	Capitalize *bool `form:"capitalize,omitempty" json:"capitalize,omitempty"`

	// IncludeNumber Include numbers in the **passphrase**.
	IncludeNumber *bool `form:"includeNumber,omitempty" json:"includeNumber,omitempty"`
}

// GetListObjectCollectionsParams defines parameters for GetListObjectCollections.
type GetListObjectCollectionsParams struct {
	// Search List only Collections that contain this search term.
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// GetListObjectFoldersParams defines parameters for GetListObjectFolders.
type GetListObjectFoldersParams struct {
	// Search List all folders that contain this search term.
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// GetListObjectItemsParams defines parameters for GetListObjectItems.
type GetListObjectItemsParams struct {
	// OrganizationId List all items with this unique Organization identifier.
	OrganizationId *openapi_types.UUID `form:"organizationId,omitempty" json:"organizationId,omitempty"`

	// CollectionId List all items with this unique collection identifier.
	CollectionId *openapi_types.UUID `form:"collectionId,omitempty" json:"collectionId,omitempty"`

	// Folderid List all items with this unique folder identifier.
	Folderid *openapi_types.UUID `form:"folderid,omitempty" json:"folderid,omitempty"`

	// Url List all items with this URL/URI value.
	Url *string `form:"url,omitempty" json:"url,omitempty"`

	// Trash List all items in the trash. This query parameter is not a true boolean, in that `?trash`, `?trash=true`, and `?trash=false` will all be interpretted as a request to list items in the trash.
	Trash *bool `form:"trash,omitempty" json:"trash,omitempty"`

	// Search List all items that contain this search term in its name, username, or URI.
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// GetListObjectOrgCollectionsParams defines parameters for GetListObjectOrgCollections.
type GetListObjectOrgCollectionsParams struct {
	// OrganizationId Unique identifier of the Organization.
	OrganizationId openapi_types.UUID `form:"organizationId" json:"organizationId"`

	// Search List only Collections that contain this search term.
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// GetListObjectOrgMembersParams defines parameters for GetListObjectOrgMembers.
type GetListObjectOrgMembersParams struct {
	// OrganizationId Unique identifier of the Organization.
	OrganizationId openapi_types.UUID `form:"organizationId" json:"organizationId"`
}

// GetListObjectOrganizationsParams defines parameters for GetListObjectOrganizations.
type GetListObjectOrganizationsParams struct {
	// Search List only Organizations that contain this search term.
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// GetListObjectSendParams defines parameters for GetListObjectSend.
type GetListObjectSendParams struct {
	// Search List all Sends that contain this search term.
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// PostMoveItemidOrganizationIdJSONBody defines parameters for PostMoveItemidOrganizationId.
type PostMoveItemidOrganizationIdJSONBody struct {
	Array *[]interface{} `json:"array,omitempty"`
}

// DeleteObjectAttachmentIdParams defines parameters for DeleteObjectAttachmentId.
type DeleteObjectAttachmentIdParams struct {
	// Itemid Unique identifier of the item the file is attached to.
	Itemid openapi_types.UUID `form:"itemid" json:"itemid"`
}

// GetObjectAttachmentIdParams defines parameters for GetObjectAttachmentId.
type GetObjectAttachmentIdParams struct {
	// Itemid Unique identifier of the item the file is attached to.
	Itemid openapi_types.UUID `form:"itemid" json:"itemid"`
}

// PostObjectOrgCollectionParams defines parameters for PostObjectOrgCollection.
type PostObjectOrgCollectionParams struct {
	// OrganizationId Unique identifier of the Organization.
	OrganizationId openapi_types.UUID `form:"organizationId" json:"organizationId"`
}

// DeleteObjectOrgCollectionIdParams defines parameters for DeleteObjectOrgCollectionId.
type DeleteObjectOrgCollectionIdParams struct {
	// OrganizationId Unique identifier of the Organization.
	OrganizationId openapi_types.UUID `form:"organizationId" json:"organizationId"`
}

// GetObjectOrgCollectionIdParams defines parameters for GetObjectOrgCollectionId.
type GetObjectOrgCollectionIdParams struct {
	// OrganizationId Unique identifier of the Organization.
	OrganizationId openapi_types.UUID `form:"organizationId" json:"organizationId"`
}

// PutObjectOrgCollectionIdParams defines parameters for PutObjectOrgCollectionId.
type PutObjectOrgCollectionIdParams struct {
	// OrganizationId Unique identifier of the Organization.
	OrganizationId openapi_types.UUID `form:"organizationId" json:"organizationId"`
}

// GetObjectTemplateTypeParamsType defines parameters for GetObjectTemplateType.
type GetObjectTemplateTypeParamsType string

// PostUnlockJSONBody defines parameters for PostUnlock.
type PostUnlockJSONBody struct {
	Password *string `json:"password,omitempty"`
}

// PostAttachmentMultipartRequestBody defines body for PostAttachment for multipart/form-data ContentType.
type PostAttachmentMultipartRequestBody PostAttachmentMultipartBody

// PostMoveItemidOrganizationIdJSONRequestBody defines body for PostMoveItemidOrganizationId for application/json ContentType.
type PostMoveItemidOrganizationIdJSONRequestBody PostMoveItemidOrganizationIdJSONBody

// PostObjectFolderJSONRequestBody defines body for PostObjectFolder for application/json ContentType.
type PostObjectFolderJSONRequestBody = Folder

// PutObjectFolderIdJSONRequestBody defines body for PutObjectFolderId for application/json ContentType.
type PutObjectFolderIdJSONRequestBody = Folder

// PostObjectItemJSONRequestBody defines body for PostObjectItem for application/json ContentType.
type PostObjectItemJSONRequestBody = ItemTemplate

// PutObjectItemIdJSONRequestBody defines body for PutObjectItemId for application/json ContentType.
type PutObjectItemIdJSONRequestBody = ItemTemplate

// PostObjectOrgCollectionJSONRequestBody defines body for PostObjectOrgCollection for application/json ContentType.
type PostObjectOrgCollectionJSONRequestBody = Collection

// PutObjectOrgCollectionIdJSONRequestBody defines body for PutObjectOrgCollectionId for application/json ContentType.
type PutObjectOrgCollectionIdJSONRequestBody = Collection

// PostObjectSendJSONRequestBody defines body for PostObjectSend for application/json ContentType.
type PostObjectSendJSONRequestBody = SendTemplate

// PutObjectSendIdJSONRequestBody defines body for PutObjectSendId for application/json ContentType.
type PutObjectSendIdJSONRequestBody = SendTemplate

// PostUnlockJSONRequestBody defines body for PostUnlock for application/json ContentType.
type PostUnlockJSONRequestBody PostUnlockJSONBody
