services:
  vault:
    image: docker.io/hashicorp/vault:1.17
    container_name: vault
    restart: on-failure:10
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: salainen-root
      VAULT_DEV_LISTEN_ADDRESS: 127.0.0.1:8200
      VAULT_ADDR: http://127.0.0.1:8200  
      VAULT_API_ADDR: http://0.0.0.0:8200  
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8200","tls_disable":"1"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
      #VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
    volumes:
      - ./config:/vault/config
      - ./data:/vault/file
      - ./logs:/vault/logs
    command: "vault server -config=/vault/config/vault.json -dev"
          